web_app/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("my/", views.bzkmz, name="bzkmz"),
    path("questions/", views.soru, name="soru"),

    path("abonelik_save/", views.email_abonelik, name="email_abonelik"),
    path("contact/", views.contact, name="contact"),

    path("login/", views.login_view, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_view, name="logout"),

    path("myprofil/", views.myprofil, name="myprofil"),
    path("mybasket/", views.mybasket, name="mybasket"),
    path("ürün/<slug:slug>", views.ürün_details, name="ürün_details"),
    path("mybasket_onay/", views.mybasket_onay, name="mybasket_onay"),
    path("create_sepet/", views.create_sepet, name="create_sepet"),
    path("sepet_delete/", views.sepet_delete, name="sepet_delete"),
    path("sepet_eksi/", views.sepet_eksi, name="sepet_eksi"),
    path("sepet_arti/", views.sepet_arti, name="sepet_arti"),
    path("imageUpdate/", views.imageUpdate, name="imageUpdate"),
    path("hesap_guncelleme/", views.hesap_guncelleme, name="hesap_guncelleme"),
]

web_app/web_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_app/templates/base.html
 {% extends "index.html" %}
 {% block content %}

 <style>
  .card:hover {
    cursor: pointer;
  }
 </style> 

      <div class="row mt-4">
          
          <!-- Ürünler Bu kısımda -->
          {% for w in ürün_list %}
          <div class="card mt-3" style="width: 17rem;">
            <a href="/ürün/{{ w.slug_ürün }}">
              <img class="card-img-top" src="{{ w.ürün_image_name.url }}" height="200" alt="Card image cap">
            </a>

            <div class="card-body">
              <a href="/ürün/{{ w.slug_ürün }}" style="color:black; text-decoration: none;">
                <h5 class="card-title">{{ w.ürün_price }} TL</h5>
                <p class="card-text">{{ w.ürün_descrption }} </p>
              </a>
              
              {% if user.is_authenticated %}
                <form action="../create_sepet/" class="mt-3" method="post">
                  {% csrf_token %}
                  <input type="text" name="ürün_name" value="{{ w.ürün_descrption }}" hidden>
                  <input type="text" name="ürün_fiyat" value="{{ w.ürün_price }}" hidden>
                  <button type="submit" class="btn btn-primary">Sepete Ekle</button>
                </form>
              {% else %}
                <a href="/login" class="btn btn-primary">
                  Sepete Ekle
                </a>
              {% endif %}


            </div>
          </div>
          {% endfor %}

        </div>
      </div>     
{% endblock %}

web_app/templates/basket.html
{% extends "index.html" %}
{% load static %}
{% block content %}

<div class="row mt-4">
</div>

<div class="row">
  <div class="col-lg-10">
    <nav aria-label="breadcrumb" class="rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="/">Ana Sayfa</a></li>
        <li class="breadcrumb-item active" aria-current="page">Sepetim</li>
        {% if sepetim %}
        <li class="breadcrumb-item"><a href="/mybasket_onay">Sepeti Onayla</a></li>
        {% else %}
        <li class="breadcrumb-item"><a href="/"></a></li>
        {% endif %}


      </ol>
    </nav>
  </div>
</div>

<div class="row">
    <div class="col-lg-8">
        <div class="cart-table-container card">
            <table class="table card-body table-cart">
                <thead>
                    <tr>
                        <th class="thumbnail-col"></th>
                        <th class="product-col">ÜRÜN</th>
                        <th class="price-col">FİYAT</th>
                        <th class="qty-col">ADET</th>
                        <th class="text-right"></th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for u in sepetim %}
                        {% if u.kullanici.username == request.user.username %}
                        {% if sepetim %}
                            <tr class="product-row">
                                <!-- Boş Alan -->
                                <td>
                                    <figure class="product-image-container">
                                            <img src="..{{ u.ürün.ürün_image_name.url }}" style="border-radius: 50%; width: 38px; height: 38px; position: relative; left:30px; top:5px;" >
                                    </figure>
                                </td>
                                <!-- Ürün İmage -->
                                <td class="product-col">
                                    <h5 class="product-title"  style="font-size:20px; line-height: 2.3;">
                                        {{ u.ürün.ürün_descrption }}
                                    </h5>
                                </td>
                                <!-- Ürün Fiyat Alanı -->
                                <td>
                                    <p style="line-height: 3;">
                                        {{ u.ürün.ürün_price }} ₺
                                    </p>
                                </td>

                                <!-- Ürün Adet Alanı -->
                                <td>
                                    <span style="position: relative; top: 10px; color:white; display: inline-block;">
                                        <form action="../sepet_eksi/" method="POST" style="display: inline-block;">
                                        {% csrf_token %}
                                            <input type="text" style="display: none;" class="form-control" name="eksideger" value="{{ u.id }}">
                                            <button type="submit" style="padding:0px 5px 0px 5px;" class="btn btn-danger">-</button>
                                        </form>

                                            <a style="padding:7px 5px 7px 5px; color:white !important; background-color: black; text-decoration: none;" class="badge badge-dark">{{ u.total_atted }}</a>

                                        <form action="../sepet_arti/" method="POST" style="display: inline-block;">
                                        {% csrf_token %}
                                            <input type="text" style="display: none;" class="form-control" name="artideger" value="{{ u.id }}">
                                            <button type="submit" style="padding:0px 5px 0px 5px;" class="btn btn-primary">+</button>
                                        </form>
                                </span>
                            </td>

                                <!-- Ürün Delete Alanı -->
                                <td class="text-right">
                                    <form action="../sepet_delete/" method="post">
                                        {% csrf_token %}
                                        <span class="subtotal-price">
                                            <div class="product-image" style="cursor: pointer; line-height: 4;">
                                                <input type="text" name="ids" value="{{ u.id }}" style="display: none;">
                                                <input type="image" src="{% static 'image/çöp.png' %}" style="border-radius: 50%; width: 30px; height: 30px;">
                                            </div>
                                        </span>
                                    </form>
                                </td>

                            </tr>          
                    
                    

                    {% else %}
                     
                    <tr class="product-row">
                        <!-- Boş Alan -->
                        <td>
                            <figure class="product-image-container">
                            </figure>
                        </td>
                        <!-- Ürün İmage -->
                        <td class="product-col">
                            <h5 class="product-title"  style="font-size:20px; line-height: 2.3;">
                                Ürün Bulunamadı
                            </h5>
                        </td>
                        <!-- Ürün Fiyat Alanı -->
                        <td>
                            <p style="line-height: 3;">
                            </p>
                        </td>

                        <!-- Ürün Adet Alanı -->
                        <td>
                            
                    </td>

                        <!-- Ürün Delete Alanı -->
                        <td class="text-right"><span class="subtotal-price">
                        </td>
                    </tr> 
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    
                            

                </tbody>

            </table>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="card" style="padding:20px">
            <h3>Sipariş Özeti</h3>

                {% if sepetim %}
                    {% if request.user.username %}
                            <table class="table table-totals">
                                <tbody>
                                    <tr>
                                        <td>Ürün Toplam</td>
                                        <td>{{ fiyat }} ₺</td>
                                    </tr>
                                </tbody>
                
                                <tfoot>
                                    
                                </tfoot>
                            </table>

                            <div class="checkout-methods">
                                <a href="/mybasket_onay" class="btn btn-block btn-dark">SEPETİ ONAYLA
                                    <i class="fa fa-arrow-right"></i>
                                </a>
                            </div>
                    {% else %}
                        <table class="table table-totals">
                            <tbody>
                                <tr>
                                    <td>Ürün Toplam</td>
                                    <td>0 ₺</td>
                                </tr>
                            </tbody>
            
                            <tfoot>
                                <tr>
                                    <td>Kargo Toplam</td>
                                    <td>0 ₺</td>
                                </tr>
                            </tfoot>     
                        </table>

                        <div class="checkout-methods">
                            <a href="#" class="btn btn-block btn-dark">SEPETİ ONAYLA
                                <i class="fa fa-arrow-right"></i></a>
                        </div>        
                    {% endif %}
                {% endif %}

        </div>
    </div>
</div>
</div>

<div class="mb-6"></div>
</main>


{% endblock %}

web_app/templates/basket_onay.html
{% extends "index.html" %}
{% load static %}
{% block content %}

<div class="row mt-4">
</div>

<div class="row">
  <div class="col-lg-10">
    <nav aria-label="breadcrumb" class="rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="/">Ana Sayfa</a></li>
        <li class="breadcrumb-item"><a href="/mybasket">Sepetim</a></li>
        <li class="breadcrumb-item active" aria-current="page">Sepeti Onayla</li>
      </ol>
    </nav>
  </div>
</div>

<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      {% for x in sepetim %}
        {% if x.kullanici.username == request.user.username %}        
        <form action="../mybasket_onay/" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="exampleInputEmail1">Teslimat Adresi</label>
                <input type="text" class="form-control" required id="exampleInputEmail1" name="adres" placeholder="Lütfen Kargo Adresinizi Giriniz">
                <input type="text" required style="display: none;" name="ids" value="{{ x.id }}">

              <small id="emailHelp" class="form-text text-muted">Siparişiniz Burada Belirtilen Adresinize Gönderilicektir.</small>
            </div>
            <br>
            <div class="form-group">
                <label for="exampleInputEmail1">Kart Numarası</label>
                <input type="text" class="form-control" required id="exampleInputEmail1" name="number" placeholder="Kart Numarası">
            </div>
            
            <div class="row mt-2">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">AY</label>
                        <select class="form-control" required name="ay" id="exampleFormControlSelect1">
                          <option>01</option>
                          <option>02</option>
                          <option>03</option>
                          <option>04</option>
                          <option>05</option>
                          <option>06</option>
                          <option>07</option>
                          <option>08</option>
                          <option>09</option>
                          <option>10</option>
                          <option>11</option>
                          <option>12</option>
                        </select>
                      </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">YIL</label>
                        <select class="form-control" required name="yil" id="exampleFormControlSelect1">
                            {% for i in yıl %}
                                <option>{{ i }}</option>
                            {% endfor %}
                        </select>
                      </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="exampleInputEmail1">CVV</label>
                        <input type="text" class="form-control" required maxlength="3" name="cvv" id="exampleInputEmail1" placeholder="CVV">
                    </div>
                </div>
            </div>
    
            <br>
            <div class="form-check">
              <input type="checkbox" required name="sözleşme" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">
                <a href="#" class="badge badge-dark" style="color:white; background-color: #343a40; text-decoration: none;">Ön Bilgilendirme Koşulları'nı ve Mesafeli Satış Sözleşmesi</a>'ni okudum, onaylıyorum.</label>
            </div>
             
            <button type="submit" class="btn mt-2 btn-outline-success">{{ fiyat }} TL Onayla</button>
        </form>    

        {% endif %}
      {% endfor %}
    </div>
    <div class="col-lg-2"> </div>
</div>


{% endblock %}

web_app/templates/bzkm.html
{% extends "index.html" %}

{% block content %}

        <div class="row mt-5" >
            
            <div class="col">
                <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d96685.69026947228!2d29.43062695310059!3d40.774607815159555!3m2!1i1024!2i768!4f13.1!5e0!3m2!1str!2str!4v1684436995923!5m2!1str!2str" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div class="col">
                <h2>Biz Kimiz</h2>
                {% for i in site %}
                <code style="color:black;">
                    {{ i.bizkmz_text }}
                </code>
                {% endfor %}
            </div>

        </div>
      </div>

      {% endblock %}

web_app/templates/iletişim.html
{% extends "index.html" %}

{% block content %}

        <div class="row mt-5" >
            
            <div class="col"></div>
            <div class="col-md-6">

                <h2>İletişim Alanı</h2>
                <form method="POST" action="/contact/">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Mail Adresiniz</label>
                        <input type="email" required name="email" class="form-control" id="exampleInputEmail1">
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Adınız Soyadınız</label>
                        <input type="text" required name="username" class="form-control" id="exampleInputPassword1">
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Lütfen Bizim İle Paylaşmak İstediklerinizi Giriniz</label>
                        <textarea class="form-control mt-2" name="isteks" id="exampleFormControlTextarea1" rows="3"></textarea>
                      </div>
                    
                    <button type="submit" class="mt-4 btn btn-primary">Gönder</button>
                </form>
            </div>
            <div class="col"></div>

        </div>
      </div>

      {% endblock %}

web_app/templates/login.html
{% extends "index.html" %}
    {% block content %}
    {% if user.is_authenticated %}
    
    <script>
      window.location.href = "http://127.0.0.1:8000/";
    </script>
        {% else %}

        <div class="row mt-4">
          
            <div class="col"></div>
            <div class="col-md-6">
                <h2>Giriş Alanı</h2>
                <form method="POST" action="/login/">
                    {% csrf_token %}
                    <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Kullanıcı Adı</label>
                    <input type="text" required name="username" class="form-control" id="exampleInputEmail1">
                    </div>
                    <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Parola</label>
                    <input type="password" required name="password" class="form-control" id="exampleInputPassword1">
                    <div id="emailHelp" class="form-text">Kayıt olmak için <a href="/register">Kayıt Alanı</a>.</div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Giriş</button>
                </form>
            </div>
            <div class="col"></div>

        </div>
      </div>

      {% endif %}

      {% endblock %}

web_app/templates/myprofil.html
{% extends "index.html" %}
{% load static %}
{% block content %}
    <style>
    .profile-pic {
    width: 200px;
    max-height: 200px;
    display: inline-block;
}

.file-upload {
    display: none !important;
}

img {
    max-width: 100%;
    height: auto;
}
.p-image {
  position: absolute;
  top: 167px;
  right: 30px;
  color: #666666;
  transition: all .3s cubic-bezier(.175, .885, .32, 1.275);
}
.p-image:hover {
  transition: all .3s cubic-bezier(.175, .885, .32, 1.275);
}
.upload-button {
  font-size: 1.2em;
}

.upload-button:hover {
  transition: all .3s cubic-bezier(.175, .885, .32, 1.275);
  color: #999;
}
</style>
    {% if user.is_authenticated %}
    <div class="row mt-4">
    </div>

    <div class="row">
      <div class="col-lg-10">
        <nav aria-label="breadcrumb" class="rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="/">Ana Sayfa</a></li>
            <li class="breadcrumb-item active" aria-current="page">Hesabım</li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        
        <div class="card mb-4">
          <div class="card-body text-center">
              {% for h in hesap %} 
                  {% if h.adi_soyadi == request.user.username %}

                    {% if h.profil_photo %}
                      <img src="..{{ h.profil_photo.url }}" class="rounded-circle img-fluid" style="width: 150px !important; height: 150px !important;">
                    {% else %}
                      <img src="{% static 'image/user.png' %}" class="rounded-circle img-fluid" style="width: 150px !important; height: 150px !important;">
                    {% endif %}  

                  {% endif %}
              {% endfor %}

            <img src="{% static 'image/imgupdate.png' %}" onclick="myfunctionClick()" id="profileImage" class="profile-pic rounded-circle " style="width: 25px; position: absolute; left:234px; top:140px; cursor:pointer">

            <form action="{% url 'users:imageUpdate' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input class="file-upload upload-button" type="file" name="image_update" id="myCheck" required/>
                <input style="display: none;" type="text" name="name" value="{{ request.user.username  }}" required/>

                <h5 class="my-3">{{ request.user.username }}</h5>
                <p class="text-muted mb-1">Yeni Kullanıcı</p>
                <p class="text-muted mb-4"></p>
                <div class="d-flex justify-content-center mb-2">
                  <button type="submit" class="btn btn-outline-success ms-1">Resim Ekle</button>
                </div>
            </form>



          </div>
        </div>
        

      <script>
        function myfunctionClick(params) {
          document.getElementById("myCheck").click();
        }
      </script>


      </div>

      <div class="col-lg-7">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Ad Soyad</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">
                  <form action="{% url 'users:hesap_guncelleme' %}" method="post" style="width: auto;">
                  {% csrf_token %}

                  {% for h in hesap %} 
                      {% if h.adi_soyadi == request.user.username %} 
                        <input type="text" value="{{ h.adi_soyadi }}" required name="username" class="form-control">
                        <input style="display: none;" type="text" name="usernameasli" required value="{{ request.user.username }}"/>
                          </p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">Email</p>
                        </div>
                        <div class="col-sm-9">
                          <p class="text-muted mb-0">
                            <input type="text" value="{{ h.email }}" required name="email" class="form-control" >  
                          </p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">Parola</p>
                        </div>
                        <div class="col-sm-9">
                          <p class="text-muted mb-0">
                            <input type="password" value="parolam" name="parolam" required class="form-control">  
                          </p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">İletişim Numarası</p>
                        </div>
                        <div class="col-sm-9">
                          <p class="text-muted mb-0">
                            <input type="text" placeholder="(000) 000 000" value="{{ h.iletişim_tel }}" required name="iletisim" class="form-control">
                          </p>
                        </div>
                      </div>
                      
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">Kargo Adresi</p>
                        </div>
                        <div class="col-sm-9">
                          <p class="text-muted mb-0">
                            <input type="text" placeholder="Lütfen Eksiksiz Giriniz !" value="{{ h.kargo_adres }}" required name="adres" class="form-control">
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-outline-success ms-1">Güncelle</button>
            </form>
            {% endif %}
            {% endfor %}

      {% else %}
        <script>
          window.location.href = "http://127.0.0.1:8000/";
        </script>
      {% endif %}
      {% endblock %}

web_app/templates/register.html
{% extends "index.html" %}
{% block content %}

{% if user.is_authenticated %}
    
<script>
  window.location.href = "http://127.0.0.1:8000/";
</script>

    {% else %}
        <div class="row mt-5" >
            
            <div class="col"></div>
            <div class="col-md-6">

                <h2>Kayıt Alanı</h2>
                <form method="POST" action="/register/">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Adınız Soyadınız</label>
                        <input type="text" required name="username" class="form-control" id="exampleInputPassword1">
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Mail Adresiniz</label>
                        <input type="email" required name="email" class="form-control" id="exampleInputEmail1">
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Parola</label>
                        <input type="password" name="password" required class="form-control" id="exampleInputPassword1">
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Parola Tekrar</label>
                        <input type="password" name="passwordx" required class="form-control" id="exampleInputPassword1">
                        <div id="emailHelp" class="form-text">Mevcut Hesabım Zaten Var <a href="/login">Giriş Alanı</a>.</div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Kayıt</button>
                </form>
            </div>
            <div class="col"></div>

          

        </div>
      </div>

      {% endif %}
      {% endblock %}

web_app/templates/setting.html
{% extends "index.html" %}
    {% block content %}
    {% if user.is_authenticated %}
    
    <div class="row mt-4">
          
        <div class="col"></div>
        <div class="col-md-6">
            <h2>Ayarlar</h2>
            
        </div>
        <div class="col"></div>

    </div>
    </div>

        {% else %}

        <script>
          window.location.href = "http://127.0.0.1:8000/";
        </script>

      {% endif %}

      {% endblock %}

web_app/templates/sorular.html
{% extends "index.html" %}
{% load static %}
{% block content %}

        <div class="row mt-5" >
            
          
            <div class="col-lg-11">

                <h2>Sıkça Sorulan Sorular</h2>
                 <br>
                  <div class="accordion" id="accordionExample">

                    {% for r in yardim %}
                  
                    <div class="accordion-item">
                      <h2 class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#{{ r.yrdm_keywords }}" aria-expanded="true" aria-controls="{{ r.yrdm_keywords }}">
                          {{ r.yrdm_title }}
                        </button>
                      </h2>
                      <div id="{{ r.yrdm_keywords }}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                          <strong>
                            {{ r.yrdm_description }}
                          </strong>
                        </div>
                      </div>
                    </div>
                    
                    {% endfor %}
                  </div>
            </div>

        </div>
      </div>

      {% endblock %}

web_app/templates/ürün_details.html
{% extends "index.html" %}
{% block content %}
<div class="row mt-4">
</div>

<div class="row">
  <div class="col-lg-10">
    <nav aria-label="breadcrumb" class="rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="/">Ana Sayfa</a></li>
        <li class="breadcrumb-item active" aria-current="page">Ürün Detay</li>
      </ol>
    </nav>
  </div>
</div>

     <div class="row mt-4">
        <div class="col-lg-2"></div>
        <div class="col-lg-4">
            <img src="{{ ürün_details_slugs.ürün_image_name.url }}" width="400" height="500">
        </div> 
        <div class="col-lg-4">
          <div style="position: relative; left:60px;">
            <h3>{{ ürün_details_slugs.ürün_descrption }}</h3>
            <h5>{{ ürün_details_slugs.ürün_price }} TL</h5>
            {% if user.is_authenticated %}
                <form action="../create_sepet/" class="mt-3" method="post">
                  {% csrf_token %}
                  <input type="text" name="ürün_name" value="{{ ürün_details_slugs.ürün_descrption }}" hidden>
                  <input type="text" name="ürün_fiyat" value="{{ ürün_details_slugs.ürün_price }}" hidden>
                  <button type="submit" class="btn btn-primary">Sepete Ekle</button>
                </form>
              {% else %}
                <a href="/login" class="btn btn-primary">
                  Sepete Ekle
                </a>
              {% endif %}
          </div>

        </div> 
        <div class="col-lg-2"></div>
      </div>
     </div>     
{% endblock %}